api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
        jsonapi:  ['application/vnd.api+json']
    swagger:
        versions: [3]
